/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package csigaverseny;

public class Gui extends javax.swing.JFrame {
    private static final int SNAIL_DEFAULT_X = 58;
    private static final int RED_SNAIL_DEFAULT_Y = 48;
    private static final int GREEN_SNAIL_DEFAULT_Y = 108;
    private static final int BLUE_SNAIL_DEFAULT_Y = 174;
    
    private IGame game;
    
    public Gui(IGame game) {
        setLayout(null);
        this.game = game;
        initComponents();
        custumizeComponents();
    }
    
    private void custumizeComponents() {
    }
    
    private void resetSnailsPos() {
        snailRed.setLocation(SNAIL_DEFAULT_X, RED_SNAIL_DEFAULT_Y);
        snailGreen.setLocation(SNAIL_DEFAULT_X, GREEN_SNAIL_DEFAULT_Y);
        snailBlue.setLocation(SNAIL_DEFAULT_X, BLUE_SNAIL_DEFAULT_Y);    
    }
    
    private void replaceSnails() {
        System.out.println("red " +snailRed.getLocation().toString());
        System.out.println("green " +snailGreen.getLocation().toString());
        System.out.println("blue " +snailBlue.getLocation().toString());
        
        
        var redDistance = game.GetSnailDistance("Red");
        var greenDistance = game.GetSnailDistance("Green");
        var blueDistance = game.GetSnailDistance("Blue");
        
        System.out.println("red " + redDistance);
        System.out.println("green " + greenDistance);
        System.out.println("blue " + blueDistance);
        
        snailRed.setLocation(SNAIL_DEFAULT_X + redDistance*20, RED_SNAIL_DEFAULT_Y);
        snailGreen.setLocation(SNAIL_DEFAULT_X + greenDistance*20, GREEN_SNAIL_DEFAULT_Y);
        snailBlue.setLocation(SNAIL_DEFAULT_X + blueDistance*20, BLUE_SNAIL_DEFAULT_Y);

        System.out.println("red " +snailRed.getLocation().toString());
        System.out.println("green " +snailGreen.getLocation().toString());
        System.out.println("blue " +snailBlue.getLocation().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        tLabel = new javax.swing.JLabel();
        sLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        aLabel = new javax.swing.JLabel();
        tLabel2 = new javax.swing.JLabel();
        snailRed = new javax.swing.JLabel();
        snailGreen = new javax.swing.JLabel();
        snailBlue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        betLabel = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        betBox = new javax.swing.JComboBox<>();
        gameState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N

        desktop.setMaximumSize(new java.awt.Dimension(30, 2147483647));

        jPanel1.setPreferredSize(new java.awt.Dimension(968, 231));

        tLabel.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        tLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLabel.setText("T");
        tLabel.setMaximumSize(new java.awt.Dimension(25, 45));
        tLabel.setMinimumSize(new java.awt.Dimension(25, 45));
        tLabel.setPreferredSize(new java.awt.Dimension(25, 45));

        sLabel.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        sLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sLabel.setText("S");
        sLabel.setMaximumSize(new java.awt.Dimension(25, 45));
        sLabel.setMinimumSize(new java.awt.Dimension(25, 45));
        sLabel.setPreferredSize(new java.awt.Dimension(25, 45));

        rLabel.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        rLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rLabel.setText("R");
        rLabel.setMaximumSize(new java.awt.Dimension(25, 45));
        rLabel.setMinimumSize(new java.awt.Dimension(25, 45));
        rLabel.setPreferredSize(new java.awt.Dimension(25, 45));

        aLabel.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        aLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aLabel.setText("A");
        aLabel.setMaximumSize(new java.awt.Dimension(25, 45));
        aLabel.setMinimumSize(new java.awt.Dimension(25, 45));
        aLabel.setPreferredSize(new java.awt.Dimension(40, 40));

        tLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 40)); // NOI18N
        tLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tLabel2.setText("T");
        tLabel2.setMaximumSize(new java.awt.Dimension(25, 45));
        tLabel2.setMinimumSize(new java.awt.Dimension(25, 45));
        tLabel2.setPreferredSize(new java.awt.Dimension(25, 45));

        snailRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csigaverseny/GuiImages/snailRed.png"))); // NOI18N

        snailGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csigaverseny/GuiImages/snailGreen.png"))); // NOI18N

        snailBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csigaverseny/GuiImages/snailBlue.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snailBlue))
                    .addComponent(tLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snailGreen)
                            .addComponent(snailRed))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(snailRed)
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snailGreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(snailBlue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        betLabel.setText("Current bet");

        startButton.setText("Start Game");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        betBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No bet placed", "Blue", "Green", "Red" }));
        betBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betBoxActionPerformed(evt);
            }
        });

        gameState.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(betLabel)
                        .addGap(42, 42, 42)
                        .addComponent(betBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(gameState, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(betLabel)
                            .addComponent(betBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(gameState, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        //resetSnailsPos();
        game.StartRace();
        gameState.setText("<html>Winner: " + game.GetWinner() + "<br>" + game.GetBetState() + "</html>");     
        replaceSnails();
    }//GEN-LAST:event_startButtonActionPerformed

    private void betBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betBoxActionPerformed
        SnailColor selected;
        switch(betBox.getSelectedIndex()) {
            case 1:
                selected = SnailColor.Blue;
                break;
            case 2:
                selected = SnailColor.Green;
                break;
            case 3:
                selected = SnailColor.Red;
                break;
            default:
                selected = SnailColor.NoColor;
        }
        game.SetCurrentBet(selected);
    }//GEN-LAST:event_betBoxActionPerformed

    public static void InitGui(IGame game) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui(game).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JComboBox<String> betBox;
    private javax.swing.JLabel betLabel;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel gameState;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel rLabel;
    private javax.swing.JLabel sLabel;
    private javax.swing.JLabel snailBlue;
    private javax.swing.JLabel snailGreen;
    private javax.swing.JLabel snailRed;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel tLabel;
    private javax.swing.JLabel tLabel2;
    // End of variables declaration//GEN-END:variables
}
